services:
  postgres:
    image: postgres:15
    container_name: boilerplate-postgres
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
      POSTGRES_DB: boilerplate-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: boilerplate-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres_data:
  minio_data: