spring:
  application:
    name: boilerplate-example
  
  datasource:
    url: jdbc:postgresql://localhost:5434/java-boilerplate-db
    username: java-boilerplate
    password: java-boilerplate
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
            
  cache:
    type: redis
    redis:
      time-to-live: 600000
      
  redis:
    host: localhost
    port: 6379

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 hours in milliseconds

minio:
  url: http://localhost:9000
  accessKey: access-key
  secretKey: secret-key
  bucketName: boilerplate-bucket

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,threaddump,httptrace
  endpoint:
    health:
      show-details: always
      
info:
  app:
    name: Boilerplate Actuator
    description: Spring Boot Boilerplate Actuator
    version: 1.0.0

logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
